[phases.setup]
nixPkgs = ["coreutils"]

[phases.build]
cmds = [
  "mkdir -p storage/app",
  "cp google-service-account.json storage/app/google-service-account.json",
  "composer install --ignore-platform-reqs",
  "npm ci",
  "npm run build"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=3000"
